export const INGREDIENT_REPOSITORY = 'INGREDIENT_REPOSITORY';
export const MENU_ITEM_REPOSITORY = 'MENU_ITEM_REPOSITORY';
export const PARENT_REPOSITORY = 'PARENT_REPOSITORY'
export const STUDENT_REPOSITORY = 'STUDENT_REPOSITORY'
export const BUCKET_REPOSITORY = 'BUCKET_REPOSITORY'
export const ORDER_REPOSITORY = 'ORDER_REPOSITORY'